### PR TITLE
Example for unioning source data

### PR DESCRIPTION
**Pull request by DylanBaker**

### CODE REVIEW

**Review by fivetran-joemarkiewicz — COMMENTED** [review]
@DylanBaker I tested this locally and was able to replicate the schema union in the transformed models! Were there any other updates you were planning to apply to this PR before converting it out of a draft? 

If not, I am comfortable transitioning the macros to dbt_fivetran_utils!

**Comment by DylanBaker** [comment]
@fivetran-joemarkiewicz Yes, I need to update the readme. I wanted to make sure we were happy with the approach. I can do that and move the macros to fivetran-utils on Monday.

**Comment by lizdeika** [comment]
Hi,
any chance for this to get merged?
It is such a waited for feature 😄

**Comment by fivetran-joemarkiewicz** [comment]
@lizdeika I hav my calendar blocked this afternoon to hopefully finish this up! 😄 🎉

**Review by fivetran-joemarkiewicz — APPROVED** [review]
LGTM - After seeing the CircleCi tests pass on the branch dependency I will approve and merge the branch to master. Thanks again so much!

**Comment by fivetran-joemarkiewicz** [comment]
@lizdeika I will be merging this branch and cutting a new release `v0.4.0` of the dbt_shopify package. This version can be expected to be live on the [dbt hub](https://hub.getdbt.com/fivetran/shopify/latest/) by the end of today or early morning tomorrow. I hope this release helps you, let me know if you have any questions!

**Comment by lizdeika** [comment]
Hi all!
I have run into one issue when one of the shopify schemas does not have one table.
I have opened a PR which should fix the thing ( not tested, not idea how ): https://github.com/fivetran/dbt_fivetran_utils/pull/33

**Pull request merged**
