### PR TITLE
Added: order_line_refunds.order_line_refund_id for shopify__orders__order_refunds.sql

### PR DESCRIPTION
**Pull request by lizdeika**
**Are you a current Fivetran customer?** 
deividas, smartbrandslaboratory

**What change(s) does this PR introduce?** 
Added: `order_line_refunds.order_line_refund_id` for `intermediate/shopify__orders__order_refunds.sql`

It is very usefull field to be used later on

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [x] No  (please provide explanation how the change is non breaking below.)

**Is this PR in response to a previously created Issue**

- [ ] Yes, Issue [link issue number here]
- [x] No 

**How did you test the PR changes?** 

 
- [ ] CircleCi  
- [x] Other (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 
- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [x] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this PR @lizdeika! 

Youopened this at the perfect time as I was just about to cut a new release for dbt 0.20.0 compatibility. I see you have added the `order_line_refund_id` field to the intermediate `shopify__orders__order_refunds` model. Is your intention that this field will flow into downstream models (ie. `shopify__orders` or `shopify__order_lines`)? 

With the current change you applied in the PR the `order_line_refund_id` field will only persist within that intermediate model. Is that the intention, or did you want this field in other models as well?

Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
@lizdeika In an effort to upgrade to close out the remaining packages with dbt 0.20.0 compatibility I will hold off on merging the PR until we have a stronger understanding of how else we can integrate the new field into the final models. 

Let me know if you have any questions, I am looking forward to being able to integrate your suggestions into the following release of dbt_shopify!

**Review by fivetran-joemarkiewicz — CHANGES_REQUESTED** [review]
See comments above for your intentions of adding this field and if you want to include it in any other models, or just the intermediate model.

Thanks!

**Comment by lizdeika** [comment]
Hi,

My intention is to build `order_returns` and `order_return_lines` in my project.
So `order_line_refund_id` is a needed field for `order_return_lines`
For now I have just copy-pasted `intermediate/shopify__orders__order_refunds.sql` source to my project's `stg_shopify__order_returns_tmp.sql` and added `order_line_refund_id`
If this would be merged, I would build my `stg_shopify__order_returns_tmp.sql` like this:
```sql
select *
from {{ ref('shopify__orders__order_refunds') }}
where restock_type = 'return'
```

**Review by fivetran-joemarkiewicz — APPROVED** [review]
Thanks for the clarification @lizdeika! This minor add looks good to me and I will go ahead and merge this into `master` to be included in the next release along with some other updates.

**Comment by fivetran-joemarkiewicz** [comment]
@lizdeika just wanted to give an update that since it is Friday and the end of the day I will want to hold off cutting an official release to the dbt hub until Monday morning when the folks as dbt-labs are back online. 

In the meantime, you can use the below config in your `packages.yml` to use the existing branch and you can follow the activity on this repo to be alerted once the official release is live on the dbt hub!

```yml
packages:
    - git: https://github.com/fivetran/dbt_shopify.git
      warn-unpinned: false
```

**Comment by fivetran-joemarkiewicz** [comment]
FYI This has been integrated into the latest release of this package. The `v0.5.1` version of the package should be live on the [dbt hub](https://hub.getdbt.com/fivetran/shopify/latest/) at the top of the hour.

Please feel open another PR or issue if you have any other questions or requests. Thank you!

**Comment by lizdeika** [comment]
Thanks! I have updated to 0.5.1 and changed my returns model. All good 👍🏽

**Pull request merged**
